import Head from "next/head";
import GradientLayout from "../components/GradientLayout";
// import avi from ""

const Home = () => {
  return (
    <GradientLayout
      title="ifedayo"
      subTitle="profile"
      image="/images/papi.jpg"
      desc="Ifedayo's profile innit"
      bg="bg-[hsl(120deg,_50%,_25%)]"
      gradient="[background-image:linear-gradient(hsl(120deg,_50%,_30%),_hsl(120deg,_50%,_20%)_40%,_hsl(120deg,_50%,_10%),_hsl(0deg,_0%,_.95%)_75%)]"
      rounded
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Main</h1>
    </GradientLayout>
  );
};

export default Home;
